[project]
site_name = "mpv"
copyright = "Copyright &copy; 2012-2025 mpv.io"
extra_css = ["assets/extra.css"]
extra_javascript = ["assets/extra.js"]

[project.extra]
generator = false

[project.theme]
language = "en"
logo = "assets/icon.png"
favicon = "assets/icon.png"
features = [
    "content.code.copy",
    "content.footnote.tooltips",
    "navigation.indexes",
    "navigation.path",
    "navigation.prune",
    "navigation.top",
    "navigation.tracking",
    "search.highlight",
    "toc.follow",
]

[[project.theme.palette]]
media = "(prefers-color-scheme)"
primary = "deep purple"
accent = "deep purple"
toggle.icon = "lucide/sun-moon"
toggle.name = "Switch to light mode"

[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
primary = "deep purple"
accent = "deep purple"
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
primary = "deep purple"
accent = "deep purple"
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to system preference"

[[project.extra.social]]
icon = "fontawesome/brands/github"
link = "https://github.com/mpv-player/mpv"

[[project.extra.social]]
icon = "fontawesome/brands/x-twitter"
link = "https://twitter.com/mpv_player"
